baseURL = 'https://kavvata.neocities.org/'
locale = 'en-us'
title = "kavvata's portfolio"
theme = 'shibui'

[languages]
  [languages.en-us]
    contentDir = 'content/en'
    languageName = 'English'
    label = 'English'
    weight = 10
  [languages.pt-br]
    contentDir = 'content/pt'
    languageName = 'Português'
    label = 'Português'
    weight = 20

[[module.mounts]]
source = 'images'
target = 'static/images'
